const PRODUCTS=[
{id:'rdp',name:'RDP Bricks',category:'brick',price:750,unit:'pallet',detail:'200 bricks / pallet',each:'R3.75 each',image:'assets/images/9.jpg',description:'Strong concrete bricks for homes, boundary walls and everyday building.'},
{id:'blocks',name:'Blocks',category:'brick',price:600,unit:'pallet',detail:'100 blocks / pallet',each:'R6.00 each',image:'assets/images/12_converted.jpeg',description:'Larger masonry units for efficient walls, extensions and local projects.'},
{id:'forehalves',name:'Forehalves',category:'brick',price:950,unit:'pallet',detail:'500 bricks / pallet',each:'R1.90 each',image:'assets/images/15_converted.jpeg',description:'Half-brick units for corners, edges and clean finishing around a build.'},
{id:'paving',name:'Paving Bricks',category:'brick',price:1000,unit:'pallet',detail:'500 bricks / pallet',each:'R2.00 each',image:'assets/images/2.jpg',description:'Durable paving for yards, walkways, driveways and outdoor spaces.'},
{id:'river-sand',name:'River Sand',category:'material',price:1000,unit:'load',detail:'Full or half loads available',image:'assets/images/material-river-sand.jpg'},
{id:'concrete-sand',name:'Concrete Sand',category:'material',price:1000,unit:'load',detail:'Full or half loads available',image:'assets/images/material-concrete-sand.jpg'},
{id:'building-soil',name:'Building Soil',category:'material',price:800,unit:'load',detail:'Full or half loads available',image:'assets/images/material-building-soil.jpg'},
{id:'river-stones',name:'River Stones',category:'material',price:1000,unit:'load',detail:'Full or half loads available',image:'assets/images/material-river-stones.jpg'}
];
const GALLERY=[
'1.jpg','2.jpg','3.jpg','4.jpg','5.jpg','6.jpg','7.jpg','8.jpg','9.jpg','10.jpg','11_converted.jpeg','12_converted.jpeg','13.jpg','14.jpg','15_converted.jpeg','16_converted.jpeg','17_converted.jpeg','18_converted.jpeg','IMG_20220507_133929_1.jpg','IMG_20220507_134019.jpg','IMG20220925071143.jpg','IMG20230115182358.jpg','IMG_1173.JPG','5F5FF3E8-2D7E-4CB6-992C-0AA279D78D45.jpeg','081A826E-F8D7-4BA0-8D7E-1B8BA8D358A8.jpeg','E5895FBE-CEED-44D7-A24A-45EA6B9FB350.jpeg','2CBF3332-0DFE-4B7F-BA6F-E7DA8ABD14D9.jpeg','580DAB2E-991F-4DC8-912E-FEA4DD042220.jpeg','AE1E90AB-60B3-4AE6-9DF9-6C30D712C343.jpeg','AA661ADB-EDBC-43CB-9E9E-ECA06B1AFAD8.jpeg'];
const state=new Map();
const q=s=>document.querySelector(s);const qa=s=>[...document.querySelectorAll(s)];
const money=n=>'R '+Math.round(n).toLocaleString('en-ZA');const product=id=>PRODUCTS.find(p=>p.id===id);
function renderProducts(){q('#brickGrid').innerHTML=PRODUCTS.filter(p=>p.category==='brick').map((p,i)=>`<article class="product-card reveal"><div class="product-image"><img src="${p.image}" alt="${p.name} supplied by Ramalepe Brickyard" loading="lazy"></div><div class="product-body"><div class="product-top"><span class="index">0${i+1}</span><span class="meta">${p.detail}</span></div><h3>${p.name}</h3><p>${p.description}</p><div class="price-row"><div class="price-stack"><small>Per pallet</small><strong>${money(p.price)}</strong><small>${p.each}</small></div><button class="add-order" data-add="${p.id}" type="button">Add to order ↗</button></div></div></article>`).join('');q('#materialGrid').innerHTML=PRODUCTS.filter(p=>p.category==='material').map((p,i)=>`<article class="material-card reveal"><div class="material-media"><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="material-body"><span class="meta">0${i+1} · ${p.detail}</span><h3>${p.name}</h3><div class="material-footer"><strong>${money(p.price)}</strong><button class="add-order" data-add="${p.id}" type="button">Add to order ↗</button></div></div></article>`).join('')}
function renderSelector(){q('#productSelector').innerHTML=PRODUCTS.map(p=>`<label class="selector"><input type="checkbox" value="${p.id}" ${state.has(p.id)?'checked':''}><span><strong>${p.name}</strong><small>${money(p.price)} / ${p.category==='brick'?'pallet':'full load'}</small></span></label>`).join('')}
function add(id,scroll=true){if(!state.has(id))state.set(id,{qty:1,loadSize:'full'});renderSelector();renderSelected();if(scroll)q('#calculator').scrollIntoView({behavior:'smooth',block:'start'})}
function remove(id){state.delete(id);renderSelector();renderSelected()}
function setQty(id,value){const it=state.get(id);if(!it)return;it.qty=Math.max(1,Math.min(999,Number(value)||1));renderSelected()}
function setLoad(id,value){const it=state.get(id);if(!it)return;it.loadSize=value;renderSelected()}
function renderSelected(){const wrap=q('#selectedItems');if(!state.size){wrap.innerHTML='<p class="empty">Choose products above to start your order.</p>';updateSummary();return}wrap.innerHTML=[...state].map(([id,it])=>{const p=product(id);return `<div class="selected-row"><div class="selected-name"><strong>${p.name}</strong><small>${p.detail}</small></div><div class="qty"><button type="button" data-minus="${id}" aria-label="Decrease ${p.name}">−</button><input type="number" min="1" max="999" value="${it.qty}" inputmode="numeric" data-qty="${id}" aria-label="Quantity for ${p.name}"><button type="button" data-plus="${id}" aria-label="Increase ${p.name}">+</button></div>${p.category==='material'?`<select class="load-select" data-load="${id}" aria-label="Load size for ${p.name}"><option value="full" ${it.loadSize==='full'?'selected':''}>Full load</option><option value="half" ${it.loadSize==='half'?'selected':''}>Half load · confirm price</option></select>`:'<span></span>'}<button class="remove" type="button" data-remove="${id}">Remove</button></div>`}).join('');updateSummary()}
function delivery(){return q('input[name="delivery"]:checked')?.value||'local'}
function calculate(){let total=0,surcharge=0,qty=0,half=false;const distant=delivery()==='distant';for(const[id,it]of state){const p=product(id);qty+=it.qty;if(p.category==='material'&&it.loadSize==='half'){half=true;if(distant)surcharge+=100*it.qty;continue}total+=p.price*it.qty;if(distant&&p.category==='material')surcharge+=100*it.qty}return{base:total,total:total+surcharge,surcharge,qty,half}}
function updateSummary(){const c=calculate();q('#summaryItems').textContent=`${state.size} item${state.size===1?'':'s'}`;q('#summaryQty').textContent=c.qty;q('#summaryDelivery').textContent=delivery()==='distant'?(c.surcharge?`+${money(c.surcharge)}`:'No material surcharge'):'Included';q('#summaryTotal').textContent=money(c.total);q('#halfLoadNotice').hidden=!c.half;q('#whatsappOrder').disabled=!state.size}
function sendWhatsApp(){if(!state.size)return;const c=calculate(),address=q('#customerAddress').value.trim(),d=delivery();const lines=['Hello Chief, I would like a quotation/order from Ramalepe Brickyard:',''];for(const[id,it]of state){const p=product(id);if(p.category==='brick')lines.push(`• ${p.name}: ${it.qty} ${it.qty===1?'pallet':'pallets'}`);else lines.push(`• ${p.name}: ${it.qty} ${it.qty===1?'load':'loads'} · ${it.loadSize==='half'?'Half load (please confirm price)':'Full load'}`)}lines.push('',`Delivery area: ${d==='local'?'Local (Lephepane / Khujwana)':'Distant (R100 per selected material load)'}`);if(address)lines.push(`Delivery address: ${address}`);if(c.surcharge)lines.push(`Material delivery surcharge: ${money(c.surcharge)}`);lines.push(`Estimated total: ${money(c.total)}`);if(c.half)lines.push('Note: Half-load base price(s) still need confirmation and are not included in the estimated total.');lines.push('','Please confirm stock, final total and delivery.');window.open(`https://wa.me/27725500640?text=${encodeURIComponent(lines.join('\n'))}`,'_blank','noopener')}
let lightboxIndex=0;function renderGallery(){q('#galleryGrid').innerHTML=GALLERY.map((f,i)=>`<button class="gallery-item ${i>=12?'hidden':''}" data-gallery="${i}" type="button"><img src="assets/images/${f}" alt="Ramalepe Brickyard work photo ${i+1}" loading="lazy"><span class="gallery-label"><span>Ramalepe / ${String(i+1).padStart(2,'0')}</span><b>View image ↗</b></span></button>`).join('')}
function openLightbox(index){lightboxIndex=(index+GALLERY.length)%GALLERY.length;q('#lightboxImage').src=`assets/images/${GALLERY[lightboxIndex]}`;q('#lightboxImage').alt=`Ramalepe Brickyard work photo ${lightboxIndex+1}`;q('#lightboxCaption').textContent=`Ramalepe / ${String(lightboxIndex+1).padStart(2,'0')} · ${lightboxIndex+1} of ${GALLERY.length}`;q('#lightbox').hidden=false;document.body.style.overflow='hidden'}function closeLightbox(){q('#lightbox').hidden=true;document.body.style.overflow=''}
renderProducts();renderSelector();renderSelected();renderGallery();
document.addEventListener('click',e=>{const a=e.target.closest('[data-add]');if(a){add(a.dataset.add);return}const m=e.target.closest('[data-minus]');if(m){setQty(m.dataset.minus,(state.get(m.dataset.minus)?.qty||1)-1);return}const p=e.target.closest('[data-plus]');if(p){setQty(p.dataset.plus,(state.get(p.dataset.plus)?.qty||1)+1);return}const r=e.target.closest('[data-remove]');if(r){remove(r.dataset.remove);return}const g=e.target.closest('[data-gallery]');if(g){openLightbox(Number(g.dataset.gallery));return}if(e.target.closest('#whatsappOrder'))sendWhatsApp();if(e.target.closest('#galleryMore')){qa('.gallery-item.hidden').forEach(el=>el.classList.remove('hidden'));q('#galleryMore').remove()}if(e.target.closest('#lightboxClose'))closeLightbox();if(e.target.closest('#lightboxPrev'))openLightbox(lightboxIndex-1);if(e.target.closest('#lightboxNext'))openLightbox(lightboxIndex+1)});
document.addEventListener('change',e=>{if(e.target.matches('#productSelector input')){e.target.checked?add(e.target.value,false):remove(e.target.value)}if(e.target.matches('[data-qty]'))setQty(e.target.dataset.qty,e.target.value);if(e.target.matches('[data-load]'))setLoad(e.target.dataset.load,e.target.value);if(e.target.matches('input[name="delivery"]'))updateSummary()});document.addEventListener('input',e=>{if(e.target.matches('[data-qty]')){const it=state.get(e.target.dataset.qty);if(it)it.qty=Math.max(1,Number(e.target.value)||1);updateSummary()}});
q('.nav-toggle').addEventListener('click',()=>{const nav=q('.nav-links');const open=nav.classList.toggle('open');q('.nav-toggle').setAttribute('aria-expanded',String(open))});qa('.nav-links a').forEach(a=>a.addEventListener('click',()=>q('.nav-links').classList.remove('open')));
document.addEventListener('keydown',e=>{if(q('#lightbox').hidden)return;if(e.key==='Escape')closeLightbox();if(e.key==='ArrowLeft')openLightbox(lightboxIndex-1);if(e.key==='ArrowRight')openLightbox(lightboxIndex+1)});
const observer='IntersectionObserver'in window?new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add('visible');observer.unobserve(x.target)}}),{threshold:.08}):null;qa('.reveal').forEach(el=>observer?observer.observe(el):el.classList.add('visible'));
